---

- name: Creates a directory for the application
  file: path={{money_tracker.app_path}} state=directory mode=0775 recurse=yes
  tags: [setupping]

- name: Clone application repo
  git:
    repo: "{{money_tracker.repo}}"
    dest: "{{money_tracker.app_path}}"
  tags: [setupping]

- name: Create database vars config
  template:
    src: pg_vars_env.j2
    dest: "{{money_tracker.app_path}}/docker/pg/vars.env"
  tags: [setupping]

- name: Create app vars config
  template:
    src: app_vars_env.j2
    dest: "{{money_tracker.app_path}}/docker/money_tracker.env"
  tags: [setupping]

- name: Build docker containers
  shell: "./docker/manager.sh build"
  args:
    chdir: "{{money_tracker.app_path}}"
  tags: [setupping]
