---

- name: Creates a directory for the application
  file: path={{money_tracker.app_path}} state=directory mode=0775 recurse=yes

- name: Clone application repo
  git:
    repo: "{{money_tracker.repo}}"
    dest: "{{money_tracker.app_path}}"
    accept_hostkey: Yes

- name: Create database vars config
  template:
    src: pg_vars_env.j2
    dest: "{{money_tracker.app_path}}/docker/pg/vars.env"

- name: Create app vars config
  template:
    src: app_vars_env.j2
    dest: "{{money_tracker.app_path}}/docker/money_tracker.env"

- name: Create init.d script for a service
  template:
    src: service.j2
    dest: "/etc/init.d/money_tracker"
    mode: "a+x"

- name: Build docker containers
  shell: "./docker/manager.sh build"
  args:
    chdir: "{{money_tracker.app_path}}"

- name: Run money tracker service
  service:
    name: money_tracker
    state: started
