---

- name: Update application repo
  git:
    repo: "{{money_tracker.repo}}"
    dest: "{{money_tracker.app_path}}"
    accept_hostkey: Yes
    clone: no
    update: yes
    force: yes
    version: "{{money_tracker.git_version}}"

- name: Run money tracker service
  service:
    name: money_tracker
    state: stopped

- name: Build docker containers
  shell: "./docker/manager.sh build"
  args:
    chdir: "{{money_tracker.app_path}}"
  register: build_result

- name: The result of building containers command
  debug:
    var: build_result

- name: Run money tracker service
  service:
    name: money_tracker
    state: started
